[2018-02-13 14:48:52 +0000] [788] [DEBUG] Current configuration:
  logger_class: gunicorn.glogging.Logger
  certfile: None
  on_starting: <function OnStarting.on_starting at 0x7f9d85c658c8>
  pre_fork: <function Prefork.pre_fork at 0x7f9d85c65d90>
  daemon: True
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-SSL': 'on', 'X-FORWARDED-PROTO': 'https'}
  proxy_allow_ips: ['127.0.0.1']
  do_handshake_on_connect: False
  group: 0
  workers: 1
  max_requests: 0
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f9d85c6c158>
  pre_exec: <function PreExec.pre_exec at 0x7f9d85c6c620>
  default_proc_name: ask.wsgi
  limit_request_line: 4094
  loglevel: debug
  logconfig: None
  syslog_prefix: None
  umask: 0
  on_reload: <function OnReload.on_reload at 0x7f9d85c65a60>
  syslog_facility: user
  preload_app: False
  worker_tmp_dir: None
  reload: False
  threads: 1
  timeout: 30
  proxy_protocol: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  worker_int: <function WorkerInt.worker_int at 0x7f9d85c6c2f0>
  worker_class: sync
  django_settings: None
  statsd_host: None
  ssl_version: 3
  worker_exit: <function WorkerExit.worker_exit at 0x7f9d85c6ca60>
  graceful_timeout: 30
  keepalive: 2
  pythonpath: None
  when_ready: <function WhenReady.when_ready at 0x7f9d85c65bf8>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f9d85c6c488>
  check_config: False
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f9d85c6cbf8>
  proc_name: None
  paste: None
  limit_request_fields: 100
  accesslog: acc.log
  spew: False
  worker_connections: 1000
  cert_reqs: 0
  suppress_ragged_eofs: True
  errorlog: error.log
  keyfile: None
  user: 0
  syslog_addr: udp://localhost:514
  chdir: /home/box/web
  bind: ['0.0.0.0:8000']
  backlog: 2048
  capture_output: False
  ca_certs: None
  limit_request_field_size: 8190
  on_exit: <function OnExit.on_exit at 0x7f9d85c6cd90>
  pidfile: None
  forwarded_allow_ips: ['127.0.0.1']
  syslog: False
  sendfile: None
  ciphers: TLSv1
  max_requests_jitter: 0
  config: None
  raw_env: []
  tmp_upload_dir: None
  enable_stdio_inheritance: False
  post_fork: <function Postfork.post_fork at 0x7f9d85c65f28>
  pre_request: <function PreRequest.pre_request at 0x7f9d85c6c7b8>
  statsd_prefix: 
  post_request: <function PostRequest.post_request at 0x7f9d85c6c8c8>
[2018-02-13 14:48:52 +0000] [788] [INFO] Starting gunicorn 19.6.0
[2018-02-13 14:48:52 +0000] [788] [DEBUG] Arbiter booted
[2018-02-13 14:48:52 +0000] [788] [INFO] Listening at: http://0.0.0.0:8000 (788)
[2018-02-13 14:48:52 +0000] [788] [INFO] Using worker: sync
[2018-02-13 14:48:52 +0000] [791] [INFO] Booting worker with pid: 791
[2018-02-13 14:48:52 +0000] [791] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named 'ask.wsgi'
[2018-02-13 14:48:52 +0000] [791] [INFO] Worker exiting (pid: 791)
[2018-02-13 14:48:52 +0000] [788] [DEBUG] 1 workers
[2018-02-13 14:48:53 +0000] [788] [INFO] Shutting down: Master
[2018-02-13 14:48:53 +0000] [788] [INFO] Reason: Worker failed to boot.
[2018-02-13 14:50:49 +0000] [878] [DEBUG] Current configuration:
  django_settings: None
  keyfile: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: TLSv1
  worker_connections: 1000
  pidfile: None
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: error.log
  syslog_facility: user
  raw_env: []
  certfile: None
  daemon: True
  user: 0
  secure_scheme_headers: {'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on', 'X-FORWARDED-PROTOCOL': 'ssl'}
  pythonpath: None
  paste: None
  ssl_version: 3
  syslog_addr: udp://localhost:514
  ca_certs: None
  pre_exec: <function PreExec.pre_exec at 0x7f7563fc5620>
  worker_class: sync
  keepalive: 2
  chdir: /home/box/web
  group: 0
  reload: False
  threads: 1
  accesslog: acc.log
  loglevel: debug
  logger_class: gunicorn.glogging.Logger
  enable_stdio_inheritance: False
  cert_reqs: 0
  when_ready: <function WhenReady.when_ready at 0x7f7563fbebf8>
  statsd_prefix: 
  limit_request_line: 4094
  limit_request_field_size: 8190
  on_starting: <function OnStarting.on_starting at 0x7f7563fbe8c8>
  logconfig: None
  check_config: False
  graceful_timeout: 30
  on_reload: <function OnReload.on_reload at 0x7f7563fbea60>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f7563fc5158>
  capture_output: False
  spew: False
  sendfile: None
  forwarded_allow_ips: ['127.0.0.1']
  pre_fork: <function Prefork.pre_fork at 0x7f7563fbed90>
  post_fork: <function Postfork.post_fork at 0x7f7563fbef28>
  worker_int: <function WorkerInt.worker_int at 0x7f7563fc52f0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f7563fc5488>
  pre_request: <function PreRequest.pre_request at 0x7f7563fc57b8>
  post_request: <function PostRequest.post_request at 0x7f7563fc58c8>
  worker_exit: <function WorkerExit.worker_exit at 0x7f7563fc5a60>
  on_exit: <function OnExit.on_exit at 0x7f7563fc5d90>
  tmp_upload_dir: None
  workers: 1
  timeout: 30
  proc_name: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f7563fc5bf8>
  preload_app: False
  worker_tmp_dir: None
  proxy_protocol: False
  max_requests: 0
  default_proc_name: ask.wsgi
  proxy_allow_ips: ['127.0.0.1']
  syslog: False
  syslog_prefix: None
  limit_request_fields: 100
  max_requests_jitter: 0
  statsd_host: None
  config: None
  umask: 0
[2018-02-13 14:50:49 +0000] [878] [INFO] Starting gunicorn 19.6.0
[2018-02-13 14:50:49 +0000] [878] [DEBUG] Arbiter booted
[2018-02-13 14:50:49 +0000] [878] [INFO] Listening at: http://0.0.0.0:8000 (878)
[2018-02-13 14:50:49 +0000] [878] [INFO] Using worker: sync
[2018-02-13 14:50:49 +0000] [881] [INFO] Booting worker with pid: 881
[2018-02-13 14:50:49 +0000] [881] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named 'ask.wsgi'
[2018-02-13 14:50:49 +0000] [881] [INFO] Worker exiting (pid: 881)
[2018-02-13 14:50:49 +0000] [878] [DEBUG] 1 workers
[2018-02-13 14:50:49 +0000] [878] [INFO] Shutting down: Master
[2018-02-13 14:50:49 +0000] [878] [INFO] Reason: Worker failed to boot.
